### PR TITLE
Feature/android notification improvements

### LINKED ISSUE #267: Add ability to provide custom intent for Shiny Notifications on Android
## Summary
The Android implementation for NotificationMananger does not expose a way to provide an alternative intent for notifications. It always uses the default launch intent for the package that is obtained from Package Manager. It would be useful for Apps with multiple activities, be able to provide an override so that notifications can be further customized.

## API Changes
1. Add a new callback method to AndroidOptions that users can provide a custom implementation for an intent builder. The default implementation should be the implementation that is currently in NotificationMananger.GetLaunchPendingIntent.
2. Modify the GetLaunchPendingIntent method in NotificationMananger to use the intent builder provided by the AndroidOptions instance defined in the notification.
3. There will be some additional work in the NotificationModule class to initial defaults for the new callback method in AndroidOptions.

## Intended Use Case
Take an Android app that contains two activities, A and B. Activity A is the "splash" activity and Activity B is the main app. If the default behavior for the NotificationManager, is to use the app's launch intent for a notification, then the App is essentially restarted, if the user taps on the notification while in the main app activity. Because the splash activity is normally not running when a notification is interacted with, the splash activity receives OnCreate and then starts the main app activity. This is a very abrupt transition for the user.

### LINKED ISSUE #274: Selecting Notification content does nothing when a NotificationCategory are supplied
## Platform

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] watchOS
 - [ ] tvOS
 - [ ] Tizen
 - [ ] .NET Standard

## Feature Library

 - [ ] Core
 - [ ] BluetoothLE
 - [ ] Beacons
 - [ ] Locations
 - [ ] HTTP Transfers
 - [X] Notifications
 - [ ] Sensors

## Version of Library
1.1.0.1473

## Version of OS(s) listed above with issue
Tested against Android API 25 - 29

## Steps to Reproduce
1. Call UseNotifications in Shiny startup with a NotiifcationDeleglate class and a supply a NotificationCategory.
2. Create a new Notification and set its Category property to the identifier specified in the NotificationCategory from 1.
3. Send the notification created in 2.
4. Tap the notification content when it appears in the Android notification area

## Expected Behavior
Tapping the notification content or on an action in the notification should cause OnEntry to be called in the NotificationDelegate.

## Actual Behavior
OnEntry is not called in the NotificationDelegate when the notification content is tapped.

### PR DESCRIPTION
**Pull request by jaredballen**
### Description of Change ###
- Replaces the current implementation for GetLaunchPendingIntent to construct an intent from the current activity context as opposed to the launch intent for the app as retrieved from Package Manager.
- Removed the branch in the Send method, so that SetContentInent is always called regardless of whether or not the notification has a category specified.

### Issues Resolved ### 
 - Fixes #274 
 - Fixes #267 

### API Changes ###
- None

### Platforms Affected ### 
- Android

### Behavioral Changes ###
- The current activity will be Resumed/Created when a notification interacted with, which is not necessarily the app's main launch activity.
- Tapping on the notification's content when a category is supplied will now call OnEntry in the NotifcationDelegate.

### Testing Procedure ###
This PR was tested using Shiny Samples-Debug.
#### #267: ####
1. Shiny Samples was modified to include a splash screen activity with the following activity attribute: `[Activity(
        Label = "Shiny",
        Icon = "@mipmap/icon",
        Theme = "@style/MainTheme",
        MainLauncher = true,
        LaunchMode = LaunchMode.SingleTop,
        NoHistory = true)]`
2. The MainActivity activity attribute was modified to the following:
`[Activity(
        Label = "Shiny",
        Icon = "@mipmap/icon",
        Theme = "@style/MainTheme",
        MainLauncher = false,
        LaunchMode = LaunchMode.SingleTop,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation
    )]`
3. In SampleStartup the following was added to the UseNotificaitons call:
`androidConfig: new AndroidOptions
                {
                    LaunchActivityFlags = AndroidActivityFlags.SingleTop,
                },`
4. Run Shiny Samples and Navigate to Notifications in Shiny Samples
5. Scroll down to 'Use Actions' and unselect the option
6. Scroll down and tap 'SEND TEST NOW'
7. The notification that appears in the OS notification area should NOT have the 'Reply', 'Yes', and 'No' actions.
8. Tap on the notification content
9. The App should resume where it was left (in the Notifications page)

#### #274: ####
1. Run Shiny Samples and Navigate to Notifications in Shiny Samples
2. Scroll down to 'Use Actions' and make sure the option is selected
3. Scroll down and tap 'SEND TEST NOW'
4. The notification that appears in the OS notification area should have the 'Reply', 'Yes', and 'No' actions.
5. Tap on the notification content, not the actions
6. The OS notification area should collapse and Shiny Samples should be resumed

### PR Checklist ###

- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by aritchie** [comment]
I can't take this PR as is.  I can only bring in your commit.  Also, I'm not even sure I agree with the changes.  I can certainly allow the launch intent to always be set, but I don't think the current activity should be used.

**Comment by jaredballen** [comment]
@aritchie I am open to suggestions concerning the activity; however, I don't think that exclusively using the launch intent from PM is the correct way to go. It is different from how notification actions are handled and I think it presents an issue for multi-activity apps. Is there a specific reason that the actions are handled with a broadcast receiver as opposed to an activity launch intent for notification actions and vice versa for the notification content intent? A new enum could be defined in `AndroidOptions` to control how the intent is created for each:
```
public enum NotificationIntnetStratagey
{
    AppLaunchIntent,
    CurrentActivity,
    BroadcastReceiver,
}
```
There would probably need to be an option for the content and for the actions, in order to maintain the current behavior.

Should this discussion be handled in #267 or is it okay to continue to use the PR?

**Comment by aritchie** [comment]
Yes - there are big reasons for the broadcast receiver.  The idea is allowing notifications to be replied to without ever entering the app.  Also, when it comes to multi-activities, my primary goal is to accomodate XF users first where usually only a single activity is in play

**Comment by jaredballen** [comment]
@aritchie, I can understand wanting to focus on XF support. That said, with most XF apps being a single activity, what is your reservation with the implementation in this PR, where the content intent is constructed for the current activity? Or what about my previous suggestion about adding support to set a preferred strategy in `AndroidOptions`?

Alternatively, I suppose it could stay the way it is. However, I think it would be helpful to expose a new method via `AndroidShinyHost` (and `PlatformExtensions`) that could be called in `OnCreate` or `OnNewIntent` of the launch activity. The method would check the intent for a notification and return the `Notification` object serialized in the intent (if there was one). This would allow the launch activity to properly route to the next activity. This is already possible if you look for the extra in the intent and then resolve the Shiny serializer to get the notification. It requires the user to hard-code the value of  `NOTIFICATION_KEY` from `AndroidNotificationProcessor`. I do not revel in the idea of hardcoding a string; but, I could live it if you did not want to expose a method for pre-parsing. Regardless, it would still cause unnecessary activity activation that I think can be avoided.

At the end of the day, I'm at your mercy on this one. I really like this library. I am using several different pieces from it and I am eager to be able to make a positive contribution to it.

**Comment by aritchie** [comment]
My reservation is that this has to all be documented, supported, and maintained going forward.  I don't really want to overcomplicate things on this if I can avoid it.  I need some time to think about how to approach this issue.  

Extension methods are already exposed for OnCreate and OnNewIntent to specifically parse out incoming notification entries.  Have you tried them?

**Comment by jaredballen** [comment]
I did not realize there were extension methods already exposed. I will take a closer look. After my comments yesterday, I did some additional testing with parsing the extra information from the intent in the launch activity. It was not as disruptive as I had originally assumed that it would be. If the extension methods that are exposed make it possible to extract the extra information form the incoming intent without hard-coding a magic string, then it probably is best to leave it the way it is.

I will review and update this PR.

**Comment by jaredballen** [comment]
@aritchie, I reviewed the static methods exposed in `Shiny.Core\Platforms\Android\PlatformExtensions` and I do not think there is an appropriate method to do what I had suggested. Yes, `ShinyOnCreate` and `ShinyOnNewIntent` can be called in the startup activity and the notification delegate will get called (indeed they will still need to be called). With that approach, there is no way to modify the startup behavior of the startup activity.

If the library remains unchanged and the application launch activity is always used, then there should be a way to modify the startup behavior of the app -- there should be a way to check the incoming intent for a notification and respond accordingly. That is not to say that the notification should be handled. Just the startup behavior should be modified if a notification is received.

This is possible now by hard coding the value of `AndroidNotificationProcessor.NOTIFICATION_KEY` in the startup activity because the `AndroidNotificationProcessor` class is private. This is a poor approach.

I suggest that a new static method be exposed in `Shiny.Core\Platforms\Android\PlatformExtensions` that would allow the user to pre-check the intent for a notification. A new method, `public static bool TryParseIntent(Intent intnet, out Notification notification)`, can be created to allow the users to pre-check intents either in `OnCreate` or `OnNewIntnet` and change how the startup activity behaves.

Thoughts? I don't want to proceed with any changes unless you agree.

**Comment by aritchie** [comment]
@jaredballen I'm not going to close this, but this isn't something I want going into the library at this time.  It's far too specific on one OS to start going down this rabbit hole.  

Most of the methods are marked virtual and can be overridden/replaced where necessary in the meantime

**Comment by jaredballen** [comment]
@aritchie, if I revert the changes associated with #267, will you still approve the changes for #274?

**Comment by aritchie** [comment]
@jaredballen This PR really has to be done fresh as it is pulling in wads of other commits.  I can fix this for 1.2 & myget later on today

**Comment by jaredballen** [comment]
@aritchie, however, you want to handle it. I just realized I set the PR to master. Sorry about that. In the future, do you prefer feature/bugfixes to be branched from master or dev? I assumed dev. Again sorry for the borked PR.

**Comment by aritchie** [comment]
@jaredballen No worries.  It will be easier for you if you put it against dev.  I usually swap the branch over in any case.  

There are two code changes put in place that should help with both of these issues

**Pull request closed without merging**
