### PR TITLE
Shiny.Localization

### PR DESCRIPTION
**Pull request by JeremyBP**
### Description of Change ###

New plugin for Shiny called Shiny.Localization.

Its main goal is to manage various text resources type (resx, json, xml, database, etc), from various origin (assembly, web service, database, etc), for various cultures, all mixed if needed.
I implemented some tests but most of all a pretty exhaustive documentation (input/docs/localization/gettingstarted.md) wich should make you understand the idea.
I also implemented the plugin into Shiny Sample wich will result in another PR to demonstrate its functionalities.

### Issues Resolved ### 

No issues but a new feature

### API Changes ###
 
 No change for existing APIs but some more for Localization

### Platforms Affected ### 

- All

### Behavioral Changes ###

None as it would be a plugin

### Testing Procedure ###
Just run the Sample and pick Localization then change the language from the picker

### PR Checklist ###

- [x] Rebased on top of the target branch at time of PR (well I used merge for this one, sorry about that)
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by aritchie** [comment]
I really appreciate the PR.  However, I really wish you had have opened an enhancement issue to see if this was a feature set the project would want to take on.  This was not on the roadmap.

The reason why I'm hesitant to take this on is because right now, I am the only developer on the project and this isn't something I necessarily want to support going forward.

**Comment by JeremyBP** [comment]
I'm sorry about the missing issue, that was something I was wondering for.
Then I realized I realy need it in my job, so I just developed it :)

I tryed to create it your way, your style. Except maybe the option builder (for fluent and infinite settings purpose), everything is written like other plugins are (well I hope so), so you could understand quickly what is done and what it is about.

When built, I published it as a private Nuget package on our Azure DevOps repo.

Finaly, when all done, I created this PR in case you think it could be part of the original Shiny project. About this, I could recreate the PR but on a dedicated branch if you wan't to play with it but the sandbox way.

If not, but think it could be useful for others, we could also publish it on public Nuget with a reshaped namespace like Shiny.Extensions.Localization or Shiny.External.Localization or whatever suit to you. A namespace allowing other developers to extend Shiny features without expending your amont maintaining work.

If not at all, I'll keep it for my personnal use, nevermind, don't be afraid to hurt me :)

At least it's already useful for my colleagues and me.

You decide :)

**Comment by aritchie** [comment]
I think this is a great chunk of code.  I think you might actually be doing yourself a bit of a disservice releasing this under Shiny (or attaching shiny to it at all).  I think you could easily make this an abstraction of it's own for any .NET ecosystem.  

If you'd still like to keep it under the Shiny name, we can discuss some different options.

**Comment by JeremyBP** [comment]
I think you're right.
If it could be useful for shiny users, it could be for non-shiny to.
I think I'll reshape it as a standalone project like Plugin.Localizer, without any Shiny dependencies.
Then maybe, I'll send you a PR for a Shiny.Integration.Localizer, wich could provide some exclusive features like autoinitialization on a shiny background job.
Sounds good to you?

**Comment by JeremyBP** [comment]
Just to let you know that, as discussed, this project is now published as Localizr on nuget and availble here https://github.com/Respawnsive/Localizr
There's no Shiny integration package as there's no Shiny specific features actualy.
We could just call services.AddLocalizr...
Regards

**Pull request closed without merging**
