### PR TITLE
iOS Background transfer create body file

### LINKED ISSUE #782: [Bug] iOS: Shiny.Net.Http upload straight to onError
### Discussed in https://github.com/shinyorg/shiny/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **GuidoNeele** November  3, 2021</sup>
I'm setting up background uploads using Shiny.Net.Http. Everything is working fine on Android but when uploading files on iOS the `IHttpTransferDelegate` `OnError` method is called straightaway with a "cancelled" exception (only a message no stacktrace). 

I've added the following code to `AppDelegate.cs`:
```csharp 
public override void HandleEventsForBackgroundUrl(UIApplication application, string sessionIdentifier, Action completionHandler)
{
      this.ShinyHandleEventsForBackgroundUrl(sessionIdentifier, completionHandler);
}
```

I think that's the only setup that needs to be done for iOS is that correct or am I missing something? 

Thanks in advance!

Guido</div>

### PR DESCRIPTION
**Pull request by GuidoNeele**
### Description of Change ###

The current iOS background transfer upload results in a file upload but it differs from the Android upload, making it harder for the backend to process the file. Some data is also missing, like post data and filename. The current upload results in the following request headers and the body is the contents of the file being uploaded.

```
X-Amzn-Trace-Id: Root=1-6184f672-0003a3447464236605440bfe
Content-Length: 89906
accept: */*
content-type: application/octet-stream
accept-language: en-US,en;q=0.9
user-agent: REMOVED/3.6.28 CFNetwork/1312 Darwin/20.6.0
accept-encoding: gzip, deflate, br
```

The current android upload looks like this:
```
X-Amzn-Trace-Id: Root=1-61853412-79a7e74e19ca5fa54b1b542a
Content-Length: 4502
Content-Type: multipart/form-data; boundary="c7891999-9ef5-41b2-af84-dc1c784ee17b"

--c7891999-9ef5-41b2-af84-dc1c784ee17b
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data.

<empty>
--c7891999-9ef5-41b2-af84-dc1c784ee17b
Content-Disposition: form-data; name=blob; filename=icon.png; filename*=utf-8''icon.png

PNG

....IHDR...9...9.............sRGB.........gAMA......a....	pHYs..........o.d....IDAThC...s.....g.....TR.~.B...mY66....%Y..:}...2>d..m.C.|...9.......L.8.$..@.	1X...;{h...7ofgfgW...............H%..:..........G.....G.F...Q...HN:k.9j..D\.{..`N.a....0......v...~[....s....P...`.#~$.C...M9.......!.{V...F..-.?..2.Z.<...C.QV.Y...`.....Jx5.{..}..:d...+>.L).N...NwR.P$..h.{xO.$J.E5,H.n..=..j&.h..c3.s9..=.`.."..................M
3...X..r[..}...=:.........H~S...G....V@......A..B...d.0...9......HYDDr.9..]_*.l..5..:.1F..z......<:p.@?....1...#...p.s....s.Yj?@c{.o.....
...etc...
--c7891999-9ef5-41b2-af84-dc1c784ee17b--
```

To recreate this request in iOS I'm creating the body in code and write that content to a file. That file is then uploaded as the body of the upload request.

Don't know if you want to go this route and certainly don't know how this is going to perform with large files. But I looked into the issue and had the code so decided to make a PR anyway.

### Issues Resolved ### 

- fixes #782 

### API Changes ###

 
 None

### Platforms Affected ### 

- iOS

### Behavioral Changes ###

None

### Testing Procedure ###

!! Didn't test this code since I wasn't able to build the source code on my mac. !!

### PR Checklist ###

- [X] Rebased on top of the target branch at time of PR
- [X] Changes adhere to coding standard
- [X] Sent to DEV branch

### CODE REVIEW

**Comment by aritchie** [comment]
@GuidoNeele - you are amazing and I love the help.  This one I need to think about.  If I do take it, your code is great and I can optimize that stream for large files.

**Comment by GuidoNeele** [comment]
Yes I fully understand that you want to think about it. I've been searching if there's a better/cleaner way of doing this but couldn't find it that quick. 

Maybe leaving the post data out completely for both Android and iOS would be easier. You can then modify the TransferJob on Android and send the file as body content, instead of the multipart/formdata, to create an equal request between platforms. Filename could be sent via a header.

**Comment by aritchie** [comment]
This now exists in preview.  I'm still working on a few weird issues with it, but the file and the headers get streamed right through, so nothing hits memory.  I've also put the file in the cache folder so the OS can decide when to flush files out.  

Thanks again for this awesome PR and suggestion

**Comment by GuidoNeele** [comment]
Great Allan! The code is much cleaner the way you wrote it! Will try to do some testing next week.

**Pull request closed without merging**
